FROM node:22-bookworm-slim

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod

COPY server ./server
COPY tsconfig.json tsconfig.node.json ./

ENV NODE_ENV=production
EXPOSE 3000

CMD ["pnpm", "server:start"]
