name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '20 3 * * 1'
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  analysis:
    name: Analyze supply-chain practices
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Run Scorecard
        uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4
        with:
          sarif_file: results.sarif
